server:
  port: 8888

users:
  home: ${user.home}

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/Desktop/study/workspace/inflearn/spring-cloud-inf-ldw/configs

debug: true
logging:
  level:
    root: debug
    org.springframework.boot.autoconfigure: error